# ===========================================================================================
# Identity Handler
# ===========================================================================================
# Purpose: Manages local user identities in the network. Each identity has a cryptographic
#          keypair for secure communication and can create/join networks via invite links.
#
# Key Functions:
# - Creates identities with public/private keypairs
# - Manages identity storage and retrieval
# - Handles invite link generation and joining
# ===========================================================================================

# Common anchors for reused data
anchors:
  # Common empty states
  emptyState: &emptyState {}
  emptyDb: &emptyDb {}

type: identity

# ===========================================================================================
# PROJECTOR - HANDLES IDENTITY EVENTS
# ===========================================================================================
projector:
  description: Stores identity information including keypairs
  func: projector.project
  
  # =======================================================================================
  # TEST SCENARIOS
  # =======================================================================================
  tests:
    # -------------------------------------------------------------------------------------
    # Test: Store New Identity
    # -------------------------------------------------------------------------------------
    - given:
        db:
          state: *emptyState
        envelope:
          data:
            type: identity
            pubkey: pub123      # Public key
            privkey: priv123    # Private key (stored securely)
            name: Alice         # Display name
          metadata: {}
      then:
        db:
          state:
            identities:
              - pubkey: pub123
                privkey: priv123
                name: Alice
          eventStore:
            - type: identity
              pubkey: pub123
              privkey: priv123
              name: Alice

# ===========================================================================================
# COMMANDS
# ===========================================================================================
commands:
  # -----------------------------------------------------------------------------------------
  # Create New Identity
  # -----------------------------------------------------------------------------------------
  create:
    description: Creates an identity with keypair and peer
    func: create.execute
    tests:
      - given:
          db: *emptyDb
          params:
            name: Bob  # Optional display name
        then:
          return:
            api_response:
              return: Identity created
              identity:
                pubkey: "*"     # Generated public key
                name: Bob
            newEvents:
              # Identity event
              - type: identity
                pubkey: "*"
                privkey: "*"    # Generated private key
                name: Bob
              # Also creates a peer event for self
              - type: peer
                pubkey: "*"     # Same as identity pubkey
                name: Bob
                
  # -----------------------------------------------------------------------------------------
  # List Identities
  # -----------------------------------------------------------------------------------------
  list:
    description: Lists all identities (without private keys)
    func: list.execute
    tests:
      - given:
          db:
            state:
              identities:
                - pubkey: pub1
                  privkey: priv1
                  name: Alice
                - pubkey: pub2
                  privkey: priv2
                  name: Bob
          params: {}
        then:
          return:
            api_response:
              return: Found 2 identities
              identities:
                # Private keys excluded from response
                - pubkey: pub1
                  name: Alice
                - pubkey: pub2
                  name: Bob
                  
  # -----------------------------------------------------------------------------------------
  # Create Invite Link
  # -----------------------------------------------------------------------------------------
  invite:
    description: Creates an invite link for sharing
    func: invite.execute
    tests:
      - given:
          db:
            state:
              identities:
                - pubkey: pub123
                  privkey: priv123
                  name: Alice
          params: {}
          identity: pub123
        then:
          return:
            api_response:
              return: Invite link created
              inviteLink: "*"        # Generated invite link
              inviteData:
                peer: pub123         # Inviter's public key
                name: Alice          # Inviter's name
                
  # -----------------------------------------------------------------------------------------
  # Join Network via Invite
  # -----------------------------------------------------------------------------------------
  join:
    description: Joins a network using an invite link
    func: join.execute
    tests:
      # -------------------------------------------------------------------------------------
      # Test: Basic Join Flow
      # -------------------------------------------------------------------------------------
      - given:
          db: *emptyDb
          params:
            # Base64-encoded invite data: {"name":"Alice","peer":"pub123"}
            inviteLink: "message-via-tor://invite/eyJuYW1lIjoiQWxpY2UiLCJwZWVyIjoicHViMTIzIn0="
            name: Charlie  # New joiner's name
        then:
          return:
            api_response:
              return: Joined network via invite
              identity:
                pubkey: "*"      # New identity's public key
                name: Charlie
              peer:
                pubkey: pub123   # Inviter's public key from link
                name: Alice      # Inviter's name from link
            newEvents:
              # New identity created
              - type: identity
                pubkey: "*"
                privkey: "*"
                name: Charlie
              # Peer event for self
              - type: peer
                pubkey: "*"
                name: Charlie
              # Peer event for inviter
              - type: peer
                pubkey: pub123
                name: Alice
                joined_via: invite    # Marks how they joined
                received_by: "*"      # New identity receives this
                
      # -------------------------------------------------------------------------------------
      # Test: Join Creates Full State
      # -------------------------------------------------------------------------------------
      - description: Join creates identity in state after projecting events
        given:
          db: *emptyDb
          params:
            # Base64-encoded invite data: {"name":"Bob","peer":"pub456"}
            inviteLink: "message-via-tor://invite/eyJuYW1lIjoiQm9iIiwicGVlciI6InB1YjQ1NiJ9"
            name: Alice
        ticks: 1  # Process events through one tick
        then:
          return:
            api_response:
              return: Joined network via invite
              identity:
                pubkey: "*"
                name: Alice
              peer:
                pubkey: pub456
                name: Bob
          db:
            state:
              # Identity created and stored
              identities:
                - pubkey: "*"
                  privkey: "*"
                  name: Alice
              # Both peers in peer list
              peers:
                # Self as peer
                - pubkey: "*"
                  name: Alice
                  joined_via: direct
                  added_at: "*"
                  received_by: "*"
                # Inviter as peer
                - pubkey: pub456
                  name: Bob
                  joined_via: invite
                  added_at: "*"
                  received_by: "*"