type: identity
projector:
  description: Stores identity information including keypairs
  func: projector.project
  tests:
    - given:
        db:
          state: {}
        envelope:
          data:
            type: identity
            pubkey: pub123
            privkey: priv123
            name: Alice
          metadata: {}
      then:
        db:
          state:
            identities:
              - pubkey: pub123
                privkey: priv123
                name: Alice
          eventStore:
            - type: identity
              pubkey: pub123
              privkey: priv123
              name: Alice
commands:
  create:
    description: Creates an identity with keypair and peer
    func: create.execute
    tests:
      - given:
          db: {}
          params:
            name: Bob
        then:
          return:
            api_response:
              return: Identity created
              identity:
                pubkey: "*"
                name: Bob
            newEvents:
              - type: identity
                pubkey: "*"
                privkey: "*"
                name: Bob
              - type: peer
                pubkey: "*"
                name: Bob
  list:
    description: Lists all identities (without private keys)
    func: list.execute
    tests:
      - given:
          db:
            state:
              identities:
                - pubkey: pub1
                  privkey: priv1
                  name: Alice
                - pubkey: pub2
                  privkey: priv2
                  name: Bob
          params: {}
        then:
          return:
            api_response:
              return: Found 2 identities
              identities:
                - pubkey: pub1
                  name: Alice
                - pubkey: pub2
                  name: Bob
  invite:
    description: Creates an invite link for sharing
    func: invite.execute
    tests:
      - given:
          db:
            state:
              identities:
                - pubkey: pub123
                  privkey: priv123
                  name: Alice
          params: {}
          identity: pub123
        then:
          return:
            api_response:
              return: Invite link created
              inviteLink: "*"
              inviteData:
                peer: pub123
                name: Alice
  join:
    description: Joins a network using an invite link
    func: join.execute
    tests:
      - given:
          db: {}
          params:
            inviteLink: "message-via-tor://invite/eyJuYW1lIjoiQWxpY2UiLCJwZWVyIjoicHViMTIzIn0="
            name: Charlie
        then:
          return:
            api_response:
              return: Joined network via invite
              identity:
                pubkey: "*"
                name: Charlie
              peer:
                pubkey: pub123
                name: Alice
            newEvents:
              - type: identity
                pubkey: "*"
                privkey: "*"
                name: Charlie
              - type: peer
                pubkey: "*"
                name: Charlie
              - type: peer
                pubkey: pub123
                name: Alice
                joined_via: invite
                received_by: "*"
      - description: Join creates identity in state after projecting events
        given:
          db: {}
          params:
            inviteLink: "message-via-tor://invite/eyJuYW1lIjoiQm9iIiwicGVlciI6InB1YjQ1NiJ9"
            name: Alice
        ticks: 1
        then:
          return:
            api_response:
              return: Joined network via invite
              identity:
                pubkey: "*"
                name: Alice
              peer:
                pubkey: pub456
                name: Bob
          db:
            state:
              identities:
                - pubkey: "*"
                  privkey: "*"
                  name: Alice
              peers:
                - pubkey: "*"
                  name: Alice
                  joined_via: direct
                  added_at: "*"
                  received_by: "*"
                - pubkey: pub456
                  name: Bob
                  joined_via: invite
                  added_at: "*"
                  received_by: "*"