openapi: 3.0.0
info:
  title: Message via Tor Protocol API
  description: API for a minimal P2P messaging network with Tor-like functionality
  version: 1.0.0

# This API only exposes user-facing operations. Internal operations like
# sync_peers, tor_simulator delivery, and incoming message processing are
# handled by background jobs triggered by the tick endpoint, not exposed
# directly as API endpoints.

paths:
  /identities:
    post:
      summary: Create a new identity
      operationId: identity.create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: []
              properties:
                name:
                  type: string
                  description: Optional name for the identity
      responses:
        201:
          description: Identity created successfully
          content:
            application/json:
              schema:
                type: object
                required: [identityId, publicKey]
                properties:
                  identityId:
                    type: string
                  publicKey:
                    type: string
    get:
      summary: List all identities
      operationId: identity.list
      responses:
        200:
          description: List of identities
          content:
            application/json:
              schema:
                type: object
                required: [identities]
                properties:
                  identities:
                    type: array
                    items:
                      type: object
                      required: [identityId, publicKey]
                      properties:
                        identityId:
                          type: string
                        publicKey:
                          type: string
                        name:
                          type: string

  /identities/{identityId}/invite:
    post:
      summary: Create an invite link
      operationId: identity.invite
      parameters:
        - name: identityId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Invite link created
          content:
            application/json:
              schema:
                type: object
                required: [inviteLink]
                properties:
                  inviteLink:
                    type: string

  /join:
    post:
      summary: Join network using invite link
      operationId: identity.join
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [inviteLink]
              properties:
                inviteLink:
                  type: string
                name:
                  type: string
                  description: Optional name for the new identity
      responses:
        201:
          description: Successfully joined network
          content:
            application/json:
              schema:
                type: object
                required: [identityId, publicKey]
                properties:
                  identityId:
                    type: string
                  publicKey:
                    type: string

  /messages:
    post:
      summary: Create a new message
      operationId: message.create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
                recipientPeerId:
                  type: string
                  description: Optional recipient peer ID
      responses:
        201:
          description: Message created
          content:
            application/json:
              schema:
                type: object
                required: [messageId, text]
                properties:
                  messageId:
                    type: string
                  text:
                    type: string

  /messages/{peerId}:
    get:
      summary: List messages for a peer
      operationId: message.list
      parameters:
        - name: peerId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
      responses:
        200:
          description: List of messages
          content:
            application/json:
              schema:
                type: object
                required: [messages]
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      required: [messageId, text, timestamp, sender]
                      properties:
                        messageId:
                          type: string
                        text:
                          type: string
                        timestamp:
                          type: integer
                        sender:
                          type: string

  /peers:
    post:
      summary: Create a new peer
      operationId: peer.create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [publicKey]
              properties:
                publicKey:
                  type: string
                name:
                  type: string
      responses:
        201:
          description: Peer created
          content:
            application/json:
              schema:
                type: object
                required: [peerId]
                properties:
                  peerId:
                    type: string

  /tick:
    post:
      summary: Run a tick cycle to process background jobs
      description: |
        Triggers all background jobs including:
        - sync_peers.sync_all - Synchronizes peer information
        - tor_simulator.deliver - Simulates Tor network delivery  
        - incoming.process_incoming - Processes incoming messages
        - unknown.purge_old - Cleans up old unknown events
      operationId: tick.run
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                time_now_ms:
                  type: integer
                  description: Current timestamp in milliseconds
      responses:
        200:
          description: Tick completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobsRun:
                    type: integer
                    description: Number of jobs executed
                  eventsProcessed:
                    type: integer
                    description: Number of events processed