# ===========================================================================================
# Unknown Event Handler
# ===========================================================================================
# Purpose: Handles unrecognized event types that arrive through the network. This handler
#          stores unknown events for potential future processing and periodically purges
#          old events to prevent unbounded storage growth.
#
# Key Functions:
# - Projector: Stores unrecognized events with metadata
# - Purge Command: Removes events older than a configured threshold
# ===========================================================================================

type: unknown

# ===========================================================================================
# PROJECTOR - HANDLES INCOMING UNKNOWN EVENTS
# ===========================================================================================
projector:
  description: Projects decrypted but unrecognized event types to state.unknown_events
  func: projector.project
  
  # =======================================================================================
  # TEST SCENARIOS
  # =======================================================================================
  tests:
    # -------------------------------------------------------------------------------------
    # Test: First Unknown Event Storage
    # -------------------------------------------------------------------------------------
    - given:
        db:
          state: {}  # Empty state
        envelope:
          data:
            type: unrecognized_type  # Event type not handled by any other handler
            data: some data
          metadata:
            eventId: event123
            origin: peer1
            receivedAt: 1000  # Timestamp in milliseconds
      then:
        db:
          state:
            unknown_events:
              - data:
                  type: unrecognized_type
                  data: some data
                metadata:
                  eventId: event123
                  origin: peer1
                  receivedAt: 1000
                timestamp: 1000  # Duplicate timestamp for easier purging
                
    # -------------------------------------------------------------------------------------
    # Test: Append to Existing Unknown Events
    # -------------------------------------------------------------------------------------
    - given:
        db:
          state:
            unknown_events:
              # Existing old unknown event
              - data:
                  type: old_type
                timestamp: 500
        envelope:
          data:
            type: another_unknown
            value: 42  # Different data structure
          metadata:
            eventId: event456
            receivedAt: 2000
      then:
        db:
          state:
            unknown_events:
              # Old event preserved
              - data:
                  type: old_type
                timestamp: 500
              # New event appended
              - data:
                  type: another_unknown
                  value: 42
                metadata:
                  eventId: event456
                  receivedAt: 2000
                timestamp: 2000

# ===========================================================================================
# COMMANDS
# ===========================================================================================
commands:
  # -----------------------------------------------------------------------------------------
  # Purge Old Events - Prevents Storage Bloat
  # -----------------------------------------------------------------------------------------
  purge_old:
    description: Purge old unknown events to prevent unbounded growth
    func: purge_old.execute
    
    # =======================================================================================
    # TEST SCENARIOS
    # =======================================================================================
    tests:
      # -------------------------------------------------------------------------------------
      # Test: Purge Events Older Than 24 Hours
      # -------------------------------------------------------------------------------------
      - given:
          db:
            state:
              unknown_events:
                # Very old event (99 seconds old)
                - data:
                    type: old_event
                  timestamp: 1000
                # Recent event (10 seconds old)
                - data:
                    type: recent_event
                  timestamp: 90000000
          params:
            current_time_ms: 100000000  # Current time
            cutoff_hours: 24           # Keep events from last 24 hours
        then:
          return:
            return: Purged 1 events
            purged: 1      # Number of events removed
            remaining: 1   # Number of events kept
            
      # -------------------------------------------------------------------------------------
      # Test: No Events to Purge
      # -------------------------------------------------------------------------------------
      - given:
          db:
            state: {}  # No unknown events
          params:
            current_time_ms: 100000000
        then:
          return:
            return: No unknown events
            purged: 0
            
# ===========================================================================================
# BACKGROUND JOB CONFIGURATION
# ===========================================================================================
# This handler runs as a background job to clean up old events
job: purge_old