type: incoming
version: 1
description: Processes incoming messages for message_via_tor protocol (no encryption)
commands:
  process_incoming:
    description: Processes incoming message queue without decryption
    func: process_incoming.execute
    tests:
      - description: Pre-decrypted envelope from tor_simulator passes through unchanged
        given:
          db:
            incoming:
              - envelope: true
                data:
                  type: message
                  text: Test
                  sender: alice
                metadata:
                  origin: network
                  receivedAt: 1000
            state: {}
          params:
            time_now_ms: 1000
        then:
          db:
            incoming: []
            eventStore:
              - type: message
                text: Test
                sender: alice
      - description: Multiple envelopes are processed in order
        given:
          db:
            incoming:
              - envelope: true
                data:
                  type: message
                  text: First
                  sender: alice
                metadata:
                  receivedAt: 1000
              - envelope: true
                data:
                  type: message
                  text: Second
                  sender: bob
                metadata:
                  receivedAt: 2000
            state:
              known_senders:
                - alice
                - bob
          params:
            time_now_ms: 3000
        then:
          db:
            incoming: []
            eventStore:
              - type: message
                text: First
                sender: alice
              - type: message
                text: Second
                sender: bob
job: process_incoming